# Generated by Django 3.2 on 2022-04-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('age', models.IntegerField(max_length=10, verbose_name='Age')),
                ('id_number', models.IntegerField(max_length=20, unique=True, verbose_name='ID Number')),
                ('job_name', models.CharField(choices=[('0', 'Technical Support'), ('1', 'Developer'), ('2', 'System Administrator'), ('3', 'Cloud Engineer'), ('4', 'Teacher'), ('5', 'General Services'), ('6', 'Student'), ('7', 'Other')], max_length=60, verbose_name='Job Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee', verbose_name='Employee Avatar')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('skills', models.ManyToManyField(to='employee.Skills')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['id'],
            },
        ),
    ]
