# Generated by Django 3.2 on 2022-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.IntegerField(unique=True, verbose_name='ID Number'),
        ),
    ]
